### ISSUE TITLE
Learned items are disappearing

### ISSUE THREAD

**Issue by jk1895** [pkmnfrk/equivalentintegrations#18] opened 2018-10-28 22:09 UTC
Hello,

I play FTB Sky Adventures and added for testing reasons your great mod. Unfortunately I found one strange bug.

First, when you add the mod after you have played a bit on your map, some learned stuff is not showing up in the attached ME-System (AE2). For example the ordinary sand. You have to unlearn it and learn it again. Then it shows up within the ME-system. The problem is, some of the new learned items disappear after a couple of minutes again. The sand stays "stable" but items like the Octadic Capacitor or the Vibrant Capacitor Bank (both Ender IO) or the dolls from Ex Nihilo Creatio disappear. I made all nine dolls and after some time five of them vanish.

You can see the items in the transmutation tablet/table but not in the ME-System.

I hope you can fix this because I suggested your mod to the modpack maker. :-)

Edit:
Other items that keep disappearing:
dark steel ingot (Ender IO), klein star up from tier two (ProjectE), mysterious magnet up from level 6 (Magic Bees)

Edit 2:
After reloading my world the vanished stuff is back again. I will keep watching...

Edit 3:
After some playing the items started to disappear again. Silver Ingots from Thermal Foundation for example. When I reload my world (not the whole game) the vanished items are back again.

Edit 4:
It's me again. New day... after restarting the whole game everything is normal. So I don't know if there is a bug or not... :) I will continue to watch it but meanwhile do with this report what you want.
Greetings

Edit 5 (The last one, I promise):
After a couple of days playing with your mod I have to say that there is this small issue with not showing up items that you have already learned and seen. You have to reload your world and they are back.

**Comment by jk1895** [comment] 2018-11-01 11:14
Edit 5 (The last one, I promise):
After a couple of days playing with your mod I have to say that there is this small issue with not showing up items that you have already learned and seen. You have to reload your world and they are back.

**Comment by pkmnfrk** [comment] 2018-11-01 23:07
This is quite interesting.

Just for references sake, can you upload a log from a time when this happens? Ideally, the first time you notice it, grab `logs/debug.log` from the pack's folder, and upload it to gist.github.com (or whatever text hosting service you prefer.)

**Comment by jk1895** [comment] 2018-11-01 23:40
Sure, I will upload a log file. But I'm not sure if I have the right one in my logs folder. There are a lot of .log.gz files, one chickens.gml, two folders (exnihilocreatio and morechickens) and a latest.log file.
No debug.log file unfortunately. Or do you need the latest.log?
When this happens, have I to quit the game and grab the file after closing it?

**Comment by pkmnfrk** [comment] 2018-11-01 23:48
Your folder will probably look something like this:

![image](https://user-images.githubusercontent.com/1333816/47886131-c02ec880-de0e-11e8-8837-a4cb4d7b8a26.png)

if you genuinely don't have a debug.log, then I guess I'll take latest.log.

Whichever one you take, you don't need to quit, just pause and even if it says (0 bytes), it will have stuff in it.

(If you want to take this conversation online, and have Discord, why not jump into the online chat, and I can help you find your debug log! https://discord.gg/PpJcSbA)

**Comment by pkmnfrk** [comment] 2018-11-01 23:59
As an aside, just to make sure, some of the items you listed in the original post (other than sand) are pretty expensive, EMC-wise. Do you have enough EMC in your system to make those items? The Transmutation Chamber won't expose those items if you don't have enough EMC for them.

(It's a long shot, but it's the only thing I can think of)

**Comment by jk1895** [comment] 2018-11-02 00:00
Sorry, my English is way too bad for discord :)

I checked every logs folder in every modpack folder and there is always only the latest.log.
I will upload these.

Yes, I have enough EMC. Billions of billions... :)

**Comment by pkmnfrk** [comment] 2018-11-02 00:14
Your English seems fine! But, that's okay.

Do you use the old-style launcher (the one that tells you about 1.11) or the new one? That might be why you don't have a debug.log? Oh well, can't be helped.

I've been (very) slowly playing through this pack (having added my own mod, of course), but I hadn't gotten to AE yet, so I copied my save, cheated it in, and set up a minimal AE system. So far, everything seems to be as normal.

How are you noticing the things missing? Is it just "Oh I need a Capacitor Bank, but hey it's missing!" or something else?

Instead of reloading the game when it happens, can you try going to the Transmutation Chamber and removing the Soulbound Talisman, then putting it back in and see if that fixes it? That should, in theory, have the same effect as reloading everything...

**Comment by jk1895** [comment] 2018-11-02 00:21
Yes, it's exactly so... yesterday, as I wrote my last edit 5 I wanted to grab a ME-export bus (AE2). But there was no export bus in the terminal (usually I could take out 1/5 million). I had to grab it from the transmutation tablet. Then i restarted the world and wrote my edit 5...

I will try it next time with the talisman.

**Comment by pkmnfrk** [comment] 2018-11-02 01:22
https://s3.amazonaws.com/pkmnfrk-minecraft-builds/pkmnfrk/equivalentintegrations/2/2.1/EquivalentIntegrations-0.1.8-PE1.3.1B.jar

Hey, so, this might be useful. I've prepared a new build that includes a command that will dump the internal data for the mod. When everything seems normal, run this command:

```
/dumpeicache
```

Then, when it next breaks, run the command again and send me latest.log. I don't know if it will be useful, but it's better than nothing.

**Comment by Astan92** [comment] 2018-11-02 19:30
I have also run into this issue. For me it's not seeing copper. Here is my latest.log

https://gist.github.com/Astan92/b19ae74f04060edd32317836bcd96f69

I'll update to the new version and try the /dumpeicache if/when it happens again

**Comment by jk1895** [comment] 2018-11-04 11:38
[latest.log](https://github.com/pkmnfrk/equivalentintegrations/files/2545776/latest.log)
Finally, I run into that issue again. This time with red matter (this red ball). I removed the Soulbound Talisman from my two chambers and put them in again but that item did not come back. I grabbed one from the table unlearned it and learned it again. Then it shows up again in the ME-system.

https://gist.github.com/jk1895/211a7507a933da4686d28c359f07af92

This time I played the Stoneblock pack and I installed your mod.
I'm not sure if I've done it right with the thedumpeicache command. I hope so.

Edit:
Also, klein star four and sphere is missing. I see them in the table but not in the ME-system.
I restarted the world and them appeared again...

Edit: the githup  paste is not complete. 
[latest.log](https://github.com/pkmnfrk/equivalentintegrations/files/2545778/latest.log)

**Comment by pkmnfrk** [comment] 2018-11-04 15:02
So, the two latest.logs you posted appear to be nearly the same, except the second one has a few extra lines about skeletons? I think it contains everything, I just want to make sure.

I just want to clarify the timing I see in the log. You:
 * loaded the world at about 11:18
 * played for about an hour
 * saw the bug at about 12:24
 * ran the dump command
 * unloaded the world at 12:45
 * immediately re-loaded it
 * ran the dump command a few minutes later (after it finished loading, presumably)

Yes? If so, then it seems like quite a few items were missing:
* Aluminum Rod
* Black Hole Band
* Body Stone
* Certus Quartz Crystal
* etc

But, besides that, I also noticed that on the first dump, there are a few items that had two entries, but only one in the second dump:

 * 1k Storage Disk
 * 1k Storage Part
 * Alchemical Coal
 * Red Matter Block (not Red Matter, which is in the first category)
 * and more!

So, all in all, very interesting... and I have no idea what might be causing it. I have been playing the same pack too, and haven't noticed the bug yet... but, it's possible that I just haven't noticed it yet.

(I did, likely unrelated to this, have a crash, after which my EMC went from ~350mil to ~10mil which was very frustrating, but I believe this was ProjectE's fault, not mine)

Let me think about this for a bit....

**Comment by jk1895** [comment] 2018-11-04 15:06
If you need more help, let me know. I will try my best.
Greetings

**Comment by pkmnfrk** [comment] 2018-11-04 15:22
Thanks! Actually, it's funny, immediately after I wrote all that, I looked at the code, and I did notice one thing I was doing slightly wrong which -- I think, in the right circumstances -- might cause the kind of issue that you are seeing.

Maybe.

So, I've fixed that, and made another build. Can you try this one out?

https://s3.amazonaws.com/pkmnfrk-minecraft-builds/pkmnfrk/equivalentintegrations/6/6.1/EquivalentIntegrations-0.1.9-PE1.3.1B.jar

It is, obviously, going to be hard to notice the issue not happening, but if we can put in about 10 hours of play each, I'll be pretty confident.

**Comment by jk1895** [comment] 2018-11-04 15:25
Sure, I will play with it as much as I can and report if I found that behavior again.

**Comment by pkmnfrk** [comment] 2018-11-04 17:14
So, I think this actually did fix it. I had observed a strange thing previously, where one of my items was showing up as 2 million items, rather than the 1 million limit the mod imposes. Looking back at my logs, I see that there indeed was a duplicate of that entry. Now, looking at a dump afterwards, I don't see any duplicates.

So, I'm going to go ahead and close this as fixed.

Thanks for your help!

**Closed as completed by pkmnfrk** 2018-11-04 17:14 UTC
Labels: bug, functionality
