### ISSUE TITLE
Transmutation Champer not learning recipes

### ISSUE THREAD

**Issue by Elmegaard** [pkmnfrk/equivalentintegrations#34] opened 2019-04-28 01:01 UTC
A Transmutation Chamber with a bound talisman and Alchemical Algorithms, do not learn the recipe for you in the transmutation table, only in anything connected to it.

I have it connected to an ME system and if I enter anything into it, it will be learned in that system, but not in my personel tablet. If I add it to my transmutation table it is also added to the ME system correctly.

This has changed recently I guess it was when I updated to 0.4.4

**Comment by pkmnfrk** [comment] 2019-04-28 13:01
Hm, I'm afraid that I'm not able to reproduce this. Oh, but you're using ProjectEX, right?

_Does more testing_

Ah, with PEX installed, I can reproduce it. This is almost certainly a bug on PEX's side, but let me dig a little bit more

**Comment by pkmnfrk** [comment] 2019-04-28 13:07
~~Nope, as usual, I am incorrect, and the bug is on my side.~~

After fixing what I thought was the bug, it's still happening. It looks like it might be a PEX bug after all....

**Comment by pkmnfrk** [comment] 2019-04-28 22:52
Actually, it is in EI, not PEX. I introduced this bug when I added PEX support. It is fixed in e38a10f

**Closed as completed by pkmnfrk** 2019-04-28 22:52 UTC
Labels: bug, functionality
